import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from 'react';
import LoadingSkeleton from "../utils/Loading";
import Navbar from "../components/Common/Navbar/Navbar";
import { SnackbarProvider } from "@/context/SnackbarContext";
import Navbar2 from "@/components/Common/Navbar2/Navbar2";
import BreadCrumbs from "@/components/Common/BreadCrumbs/BreadCrumbs";
import Footer from "@/components/Common/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next App Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SnackbarProvider>
          <Navbar />
          <Navbar2 />
          <BreadCrumbs />
          <Suspense fallback={<LoadingSkeleton />}>
            {children}
          </Suspense>
          <Footer />
        </SnackbarProvider>

      </body>
    </html>
  );
}
