import { Onest } from 'next/font/google'


import "./globals.css";
import { Suspense } from 'react';
import LoadingSkeleton from "../utils/Loading";
import Navbar from "../components/Common/Navbar/Navbar";
import { SnackbarProvider } from "@/context/SnackbarContext";
import Navbar2 from "@/components/Common/Navbar2/Navbar2";
import BreadCrumbs from "@/components/Common/BreadCrumbs/BreadCrumbs";
import Footer from "@/components/Common/Footer/Footer";
import { CartProvider } from '@/context/CartContext';

const onest = Onest({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "SteadfastIT E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${onest.className} antialiased`}
      >
        <SnackbarProvider>
          <CartProvider>
            <Navbar />
            <Navbar2 />
            <BreadCrumbs />
            <Suspense fallback={<LoadingSkeleton />}>
              {children}
            </Suspense>
            <Footer />
          </CartProvider>
        </SnackbarProvider>

      </body>
    </html>
  );
}
